Fix the build of popover_menu.
On a machine with gtk+-3.16 I previously got:

  src/lib.rs:221:5: 221:16 error: unresolved import `self::widgets::PopoverMenu`. There is no `PopoverMenu` in `widgets` [E0432]
  src/lib.rs:221     PopoverMenu
                   ^~~~~~~~~~~

because popover menu was being referenced in lib.rs, but the popover_menu
module was never imported. Once that was fixed, popover_menu didn't quite
compile. This commit fixes both issues.